name: BlockFonts
version: ${project.version}
main: com.timewars.blockfonts.BlockFonts
api-version: 1.16
authors: [ Vitshev ]
description: Plugin to get ability to create block texts
depend:
  - Triton
  - WorldEdit
commands:
  textFrame:
    description: Main BlockFonts Command
    usage: |
      /<command> create <frame-name> - create text frame.
      /<command> remove <frame-name> - remove text frame.
      /<command> addLangFrame <frame-name> <lang> - add lang for frame.
      /<command> removeLangFrame <frame-name> <lang> - remove lang from frame.
permissions:
  blockFonts.use:
    default: op
    description: Use the plugin config